/**
 * Maps wiki location strings (from quest/boss infoboxes) to our region IDs.
 *
 * The OSRS Wiki uses specific location names ("Lumbridge Castle", "God Wars Dungeon")
 * that must map to our 14 canonical region IDs defined in osrs-regions.ts.
 *
 * DT2 boss regions follow Jagex league classifications (DP/RE wiki pages),
 * which may differ from geographic location.
 */

const LOCATION_KEYWORDS: [string, string][] = [
  // Misthalin
  ["lumbridge", "misthalin"],
  ["varrock", "misthalin"],
  ["draynor", "misthalin"],
  ["edgeville", "misthalin"],
  ["barbarian village", "misthalin"],
  ["champions' guild", "misthalin"],
  ["cooks' guild", "misthalin"],
  ["digsite", "misthalin"],
  ["dig site", "misthalin"],
  ["grand exchange", "misthalin"],
  ["abyss", "misthalin"],
  ["abyssal nexus", "misthalin"],
  ["misthalin", "misthalin"],
  ["dorgesh-kaan", "misthalin"],
  ["dorgesh kaan", "misthalin"],
  ["paterdomus", "misthalin"],
  ["exam centre", "misthalin"],
  ["soul wars", "misthalin"],

  // Karamja
  ["karamja", "karamja"],
  ["brimhaven", "karamja"],
  ["tai bwo wannai", "karamja"],
  ["shilo village", "karamja"],
  ["tzhaar", "karamja"],
  ["mor ul rek", "karamja"],
  ["musa point", "karamja"],
  ["crandor", "karamja"],
  ["fight cave", "karamja"],
  ["inferno", "karamja"],
  ["tzkal", "karamja"],
  ["tztok", "karamja"],
  ["kharazi", "karamja"],

  // Asgarnia
  ["falador", "asgarnia"],
  ["port sarim", "asgarnia"],
  ["rimmington", "asgarnia"],
  ["taverley", "asgarnia"],
  ["burthorpe", "asgarnia"],
  ["dwarven mine", "asgarnia"],
  ["ice mountain", "asgarnia"],
  ["white wolf mountain", "asgarnia"],
  ["god wars dungeon", "asgarnia"],
  ["warriors' guild", "asgarnia"],
  ["warriors guild", "asgarnia"],
  ["death plateau", "asgarnia"],
  ["troll stronghold", "asgarnia"],
  ["trollheim", "asgarnia"],
  ["asgarnia", "asgarnia"],
  ["mudskipper point", "asgarnia"],
  ["thurgo", "asgarnia"],
  ["black knights", "asgarnia"],
  ["monastery", "asgarnia"],
  ["cerberus' lair", "asgarnia"],
  ["key master", "asgarnia"],
  ["camdozaal", "asgarnia"],
  ["corsair cove", "asgarnia"],
  ["corsair", "asgarnia"],
  ["lassar", "asgarnia"],
  ["whisperer", "asgarnia"],

  // Kandarin
  ["ardougne", "kandarin"],
  ["camelot", "kandarin"],
  ["catherby", "kandarin"],
  ["seers' village", "kandarin"],
  ["seers village", "kandarin"],
  ["yanille", "kandarin"],
  ["ranging guild", "kandarin"],
  ["tree gnome stronghold", "kandarin"],
  ["tree gnome village", "kandarin"],
  ["otto's grotto", "kandarin"],
  ["fishing guild", "kandarin"],
  ["legends' guild", "kandarin"],
  ["kandarin", "kandarin"],
  ["witchaven", "kandarin"],
  ["port khazard", "kandarin"],
  ["fight arena", "kandarin"],
  ["watchtower", "kandarin"],
  ["observatory", "kandarin"],
  ["underground pass", "kandarin"],
  ["khazard", "kandarin"],
  ["smoke devil", "kandarin"],
  ["thermonuclear", "kandarin"],
  ["piscatoris", "kandarin"],
  ["feldip", "kandarin"],
  ["castle wars", "kandarin"],
  ["barbarian outpost", "kandarin"],
  ["hemenster", "kandarin"],
  ["eagles' peak", "kandarin"],
  ["eagles peak", "kandarin"],
  ["tower of life", "kandarin"],
  ["nightmare zone", "kandarin"],

  // Fremennik
  ["rellekka", "fremennik"],
  ["neitiznot", "fremennik"],
  ["jatizso", "fremennik"],
  ["waterbirth", "fremennik"],
  ["lunar isle", "fremennik"],
  ["fremennik", "fremennik"],
  ["trollweiss", "fremennik"],
  ["weiss", "fremennik"],
  ["keldagrim", "fremennik"],
  ["miscellania", "fremennik"],
  ["etceteria", "fremennik"],
  ["ungael", "fremennik"],
  ["vorkath", "fremennik"],
  ["ghorrock", "fremennik"],
  ["dagannoth", "fremennik"],
  ["jormungand", "fremennik"],
  ["mountain camp", "fremennik"],
  ["lithkren", "fremennik"],
  ["muspah", "fremennik"],
  ["duke sucellus", "fremennik"],

  // Morytania
  ["canifis", "morytania"],
  ["port phasmatys", "morytania"],
  ["phasmatys", "morytania"],
  ["barrows", "morytania"],
  ["slayer tower", "morytania"],
  ["darkmeyer", "morytania"],
  ["ver sinhaza", "morytania"],
  ["morytania", "morytania"],
  ["theatre of blood", "morytania"],
  ["haunted mine", "morytania"],
  ["burgh de rott", "morytania"],
  ["slepe", "morytania"],
  ["meiyerditch", "morytania"],
  ["mort myre", "morytania"],
  ["mort'ton", "morytania"],
  ["nightmare", "morytania"],
  ["phosani", "morytania"],
  ["grotesque guardians", "morytania"],
  ["sisterhood sanctuary", "morytania"],
  ["sisterhood", "morytania"],
  ["hallowed sepulchre", "morytania"],
  ["fenkenstrain", "morytania"],
  ["mos le'harmless", "morytania"],
  ["mos le harmless", "morytania"],

  // Desert
  ["al kharid", "desert"],
  ["pollnivneach", "desert"],
  ["sophanem", "desert"],
  ["nardah", "desert"],
  ["kalphite", "desert"],
  ["desert", "desert"],
  ["kharidian", "desert"],
  ["bedabin", "desert"],
  ["shantay pass", "desert"],
  ["bandit camp", "desert"],
  ["menaphos", "desert"],
  ["jaldraocht", "desert"],
  ["agility pyramid", "desert"],
  ["tempoross", "desert"],
  ["ruins of unkah", "desert"],
  ["ruins of ullek", "desert"],
  ["tombs of amascut", "desert"],
  ["uzer", "desert"],
  ["dominion tower", "desert"],
  ["smoke dungeon", "desert"],
  ["giants' foundry", "desert"],
  ["giants foundry", "desert"],
  ["necropolis", "desert"],
  ["the scar", "desert"],
  ["leviathan", "desert"],

  // Tirannwn
  ["prifddinas", "tirannwn"],
  ["lletya", "tirannwn"],
  ["iorwerth", "tirannwn"],
  ["isafdar", "tirannwn"],
  ["tirannwn", "tirannwn"],
  ["elven", "tirannwn"],
  ["arandar", "tirannwn"],
  ["gauntlet", "tirannwn"],
  ["zalcano", "tirannwn"],
  ["zul-andra", "tirannwn"],
  ["zulrah", "tirannwn"],
  ["poison waste", "tirannwn"],
  ["kraken cove", "kandarin"],
  ["kraken", "kandarin"],

  // Wilderness
  ["wilderness", "wilderness"],
  ["revenant cave", "wilderness"],
  ["revenant", "wilderness"],
  ["mage arena", "wilderness"],
  ["chaos temple", "wilderness"],
  ["ferox enclave", "wilderness"],
  ["deep wilderness", "wilderness"],
  ["lava maze", "wilderness"],
  ["corporeal beast", "wilderness"],
  ["resource area", "wilderness"],
  ["rogues' castle", "wilderness"],
  ["chaos altar", "wilderness"],
  ["scorpion pit", "wilderness"],
  ["callisto", "wilderness"],
  ["venenatis", "wilderness"],
  ["vet'ion", "wilderness"],
  ["king black dragon", "wilderness"],
  ["chaos fanatic", "wilderness"],
  ["scorpia", "wilderness"],
  ["crazy archaeologist", "wilderness"],
  ["chaos elemental", "wilderness"],
  ["web chasm", "wilderness"],
  ["silk chasm", "wilderness"],
  ["spindel", "wilderness"],
  ["artio", "wilderness"],
  ["calvar'ion", "wilderness"],
  ["fountain of rune", "wilderness"],

  // Kebos
  ["farming guild", "kebos"],
  ["mount karuulm", "kebos"],
  ["karuulm", "kebos"],
  ["kebos", "kebos"],
  ["battlefront", "kebos"],
  ["hydra", "kebos"],
  ["konar", "kebos"],
  ["molch", "kebos"],
  ["hespori", "kebos"],

  // Kourend
  ["arceuus", "kourend"],
  ["hosidius", "kourend"],
  ["lovakengj", "kourend"],
  ["piscarilius", "kourend"],
  ["shayzien", "kourend"],
  ["kourend", "kourend"],
  ["zeah", "kourend"],
  ["chambers of xeric", "kourend"],
  ["wintertodt", "kourend"],
  ["catacombs of kourend", "kourend"],
  ["catacomb", "kourend"],
  ["fortis colosseum", "varlamore"],
  ["great kourend", "kourend"],
  ["mount quidamortem", "kourend"],
  ["beneath kourend", "kourend"],
  ["forthos", "kourend"],
  ["sarachnis", "kourend"],
  ["skotizo", "kourend"],
  ["chasm of fire", "kourend"],
  ["yama", "kourend"],
  ["woodcutting guild", "kourend"],

  // Fossil Island
  ["fossil island", "fossil-island"],
  ["volcanic mine", "fossil-island"],
  ["mushroom forest", "fossil-island"],
  ["deranged archaeologist", "fossil-island"],

  // Varlamore
  ["varlamore", "varlamore"],
  ["civitas illa fortis", "varlamore"],
  ["cam torum", "varlamore"],
  ["hunter guild", "varlamore"],
  ["colosseum", "varlamore"],
  ["tapoyauik", "varlamore"],
  ["ruins of tapoyauik", "varlamore"],
  ["ralos' rise", "varlamore"],
  ["hueycoatl", "varlamore"],
  ["mokhaiotl", "varlamore"],
  ["shellbane", "varlamore"],
  ["perilous moon", "varlamore"],
  ["blood moon", "varlamore"],
  ["blue moon", "varlamore"],
  ["eclipse moon", "varlamore"],
  ["gemstone crab", "varlamore"],
  ["tlati", "varlamore"],
  ["neypotzli", "varlamore"],
  ["aldarin", "varlamore"],
  ["stranglewood", "varlamore"],
  ["vardorvis", "varlamore"],

  // Zanaris / Other — Zanaris accessible everywhere in DP, map to kandarin as default
  ["zanaris", "kandarin"],
  ["entrana", "kandarin"],
  ["ape atoll", "karamja"],
  ["fairy ring", "kandarin"],
  ["cosmic altar", "kandarin"],
];

/**
 * Map a wiki location string to one of our region IDs.
 * Performs case-insensitive keyword matching.
 * Returns "misthalin" as fallback for unmatched locations.
 */
export function mapLocationToRegion(locationText: string): string {
  const lower = locationText.toLowerCase();

  for (const [keyword, regionId] of LOCATION_KEYWORDS) {
    if (lower.includes(keyword)) return regionId;
  }

  return "misthalin";
}
